-- ============================================================================
-- ESQUEMA Y SEEDERS PROFESIONALES DE POSTGRESQL (POSTGRES-PRO)
-- Proyecto: Tienda Doña Paty
-- Compatible con: PostgreSQL 14+, Neon, Supabase, Vercel Postgres, AWS RDS
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. Limpieza de Tablas (Orden inverso de dependencias)
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS detalle_pedido_cliente CASCADE;
DROP TABLE IF EXISTS pedido_cliente CASCADE;
DROP TABLE IF EXISTS configuracion_transferencia CASCADE;
DROP TABLE IF EXISTS detventa CASCADE;
DROP TABLE IF EXISTS venta CASCADE;
DROP TABLE IF EXISTS movimiento_caja CASCADE;
DROP TABLE IF EXISTS sesion_caja CASCADE;
DROP TABLE IF EXISTS detcompra CASCADE;
DROP TABLE IF EXISTS compra CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS categoria CASCADE;
DROP TABLE IF EXISTS marca CASCADE;
DROP TABLE IF EXISTS proveedor CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS empleados CASCADE;
DROP TABLE IF EXISTS cargo CASCADE;
DROP TABLE IF EXISTS sucursal CASCADE;
DROP TABLE IF EXISTS direccion CASCADE;

-- ----------------------------------------------------------------------------
-- 2. Creación de Tablas con Tipos Nativos y Claves Foráneas Explícitas
-- ----------------------------------------------------------------------------

-- Tabla: direccion
CREATE TABLE direccion (
  idDir INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pais VARCHAR(50) DEFAULT 'México',
  estado VARCHAR(50) DEFAULT 'México',
  municipio VARCHAR(50),
  colonia VARCHAR(50),
  calle VARCHAR(50),
  noExt VARCHAR(10),
  noInt VARCHAR(10),
  codPostal VARCHAR(10)
);

-- Tabla: sucursal
CREATE TABLE sucursal (
  idSuc INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombreSuc VARCHAR(100) NOT NULL,
  descripcionSuc VARCHAR(255),
  telefonoSuc VARCHAR(15),
  correoSuc VARCHAR(100),
  paginaWebSuc VARCHAR(100),
  redSocialSuc VARCHAR(100),
  logoSuc TEXT,
  idDir INT REFERENCES direccion(idDir) ON DELETE SET NULL
);

-- Tabla: cargo
CREATE TABLE cargo (
  idCargo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombreCargo VARCHAR(100) NOT NULL,
  descripcionCargo VARCHAR(200),
  idSuc INT NOT NULL REFERENCES sucursal(idSuc) ON DELETE CASCADE,
  CONSTRAINT uq_cargo_sucursal_nombre UNIQUE (idSuc, nombreCargo)
);

-- Tabla: empleados
CREATE TABLE empleados (
  idEmp INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombreEmp VARCHAR(100) NOT NULL,
  apellidoPatEmp VARCHAR(100),
  apellidoMatEmp VARCHAR(100),
  edadPer INT,
  generoPer VARCHAR(20),
  fechaIngreso DATE DEFAULT CURRENT_DATE,
  fechaEntrada DATE,
  fechaSalida DATE,
  correoEmp VARCHAR(100) UNIQUE NOT NULL,
  contrasenaHash VARCHAR(255),
  estadoEmp BOOLEAN NOT NULL DEFAULT TRUE,
  googleSub VARCHAR(255) UNIQUE,
  telefono VARCHAR(15),
  fotoPerfil TEXT,
  idDir INT REFERENCES direccion(idDir) ON DELETE SET NULL,
  idCargo INT REFERENCES cargo(idCargo) ON DELETE SET NULL
);

-- Tabla: cliente
CREATE TABLE cliente (
  idCliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombreCliente VARCHAR(100) NOT NULL,
  apellidoPatCliente VARCHAR(100),
  apellidoMatCliente VARCHAR(100),
  correoCliente VARCHAR(150) UNIQUE NOT NULL,
  googleSub VARCHAR(255) UNIQUE NOT NULL,
  fotoPerfil TEXT,
  estadoCliente BOOLEAN NOT NULL DEFAULT TRUE,
  fechaRegistro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultimoAcceso TIMESTAMPTZ
);

-- Tabla: categoria
CREATE TABLE categoria (
  idCat INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombreCat VARCHAR(100) NOT NULL,
  descripCat VARCHAR(200)
);

-- Tabla: marca
CREATE TABLE marca (
  idMarca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombreMarca VARCHAR(100) NOT NULL,
  descripMarca VARCHAR(200)
);

-- Tabla: proveedor
CREATE TABLE proveedor (
  idProv INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombreProv VARCHAR(100) NOT NULL,
  telefonoProv VARCHAR(15),
  correoProv VARCHAR(100),
  pagwebProv VARCHAR(100),
  redsocialProv VARCHAR(100),
  idDir INT REFERENCES direccion(idDir) ON DELETE SET NULL
);

-- Tabla: productos
CREATE TABLE productos (
  idPro INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombrePro VARCHAR(100) NOT NULL,
  precioVentaPro NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  costoPro NUMERIC(10,2) DEFAULT 0.00,
  existenciaPro INT NOT NULL DEFAULT 0,
  stockMinimoPro INT DEFAULT 1,
  tamanoPro VARCHAR(50),
  presentacionPro VARCHAR(50),
  tipoPro VARCHAR(50),
  codigoQR VARCHAR(200) UNIQUE,
  skuPro VARCHAR(100),
  imagenPro TEXT,
  activoPro BOOLEAN NOT NULL DEFAULT TRUE,
  idMarca INT REFERENCES marca(idMarca) ON DELETE SET NULL,
  idCat INT REFERENCES categoria(idCat) ON DELETE SET NULL
);

-- Tabla: compra
CREATE TABLE compra (
  idCompra INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fechaCompra DATE DEFAULT CURRENT_DATE,
  horaCompra TIME DEFAULT CURRENT_TIME,
  totalCompra NUMERIC(10,2) DEFAULT 0.00,
  idProv INT REFERENCES proveedor(idProv) ON DELETE SET NULL,
  idSuc INT REFERENCES sucursal(idSuc) ON DELETE SET NULL,
  idEmp INT REFERENCES empleados(idEmp) ON DELETE SET NULL
);

-- Tabla: detcompra
CREATE TABLE detcompra (
  idDetCompra INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idCompra INT NOT NULL REFERENCES compra(idCompra) ON DELETE CASCADE,
  idPro INT NOT NULL REFERENCES productos(idPro) ON DELETE RESTRICT,
  cantidadDetCompra INT DEFAULT 1,
  subtotalDetCompra NUMERIC(10,2) DEFAULT 0.00
);

-- Tabla: sesion_caja
CREATE TABLE sesion_caja (
  idSesionCaja INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuidSesionCaja CHAR(36) UNIQUE,
  idEmp INT NOT NULL REFERENCES empleados(idEmp) ON DELETE RESTRICT,
  idSuc INT NOT NULL REFERENCES sucursal(idSuc) ON DELETE RESTRICT,
  fechaHoraApertura TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fondoInicial NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  fechaHoraCierre TIMESTAMPTZ,
  totalVentas NUMERIC(10,2),
  totalEfectivo NUMERIC(10,2),
  totalTarjeta NUMERIC(10,2),
  totalTransferencia NUMERIC(10,2),
  totalIngresos NUMERIC(10,2),
  totalRetiros NUMERIC(10,2),
  efectivoEsperado NUMERIC(10,2),
  efectivoContado NUMERIC(10,2),
  diferencia NUMERIC(10,2),
  numeroVentas INT,
  estado VARCHAR(20) NOT NULL DEFAULT 'ABIERTA',
  observaciones VARCHAR(255)
);

-- Tabla: movimiento_caja
CREATE TABLE movimiento_caja (
  idMovimientoCaja INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuidMovimientoCaja CHAR(36) UNIQUE,
  idSesionCaja INT NOT NULL REFERENCES sesion_caja(idSesionCaja) ON DELETE CASCADE,
  tipoMovimiento VARCHAR(20) NOT NULL, -- INGRESO, RETIRO
  monto NUMERIC(10,2) NOT NULL,
  concepto VARCHAR(255) NOT NULL,
  fechaHora TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  idEmp INT NOT NULL REFERENCES empleados(idEmp) ON DELETE RESTRICT
);

-- Tabla: venta
CREATE TABLE venta (
  idVenta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuidVenta CHAR(36) UNIQUE,
  fechaVenta DATE DEFAULT CURRENT_DATE,
  horaVenta TIME DEFAULT CURRENT_TIME,
  total NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  metodoPago VARCHAR(20) NOT NULL DEFAULT 'EFECTIVO', -- EFECTIVO, TARJETA, TRANSFERENCIA
  montoRecibido NUMERIC(10,2),
  cambio NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  estadoVenta VARCHAR(20) NOT NULL DEFAULT 'COMPLETADA', -- COMPLETADA, CANCELADA
  fechaCancelacion TIMESTAMPTZ,
  motivoCancelacion VARCHAR(255),
  idEmpCancela INT REFERENCES empleados(idEmp) ON DELETE SET NULL,
  idEmp INT REFERENCES empleados(idEmp) ON DELETE SET NULL,
  idSuc INT NOT NULL REFERENCES sucursal(idSuc) ON DELETE RESTRICT,
  idSesionCaja INT REFERENCES sesion_caja(idSesionCaja) ON DELETE SET NULL
);

-- Tabla: detventa
CREATE TABLE detventa (
  idDetVenta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idVenta INT NOT NULL REFERENCES venta(idVenta) ON DELETE CASCADE,
  idPro INT NOT NULL REFERENCES productos(idPro) ON DELETE RESTRICT,
  cantidadDetVenta INT NOT NULL DEFAULT 1,
  precioUnitarioDetVenta NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  subtotalDetVenta NUMERIC(10,2) NOT NULL DEFAULT 0.00
);

-- Tabla: configuracion_transferencia
CREATE TABLE configuracion_transferencia (
  idConfiguracion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idSuc INT NOT NULL UNIQUE REFERENCES sucursal(idSuc) ON DELETE CASCADE,
  banco VARCHAR(100) NOT NULL,
  titular VARCHAR(150) NOT NULL,
  clabe VARCHAR(18),
  numeroCuenta VARCHAR(50),
  instrucciones VARCHAR(1000),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fechaActualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Tabla: pedido_cliente
CREATE TABLE pedido_cliente (
  idPedido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuidPedido CHAR(36) UNIQUE NOT NULL,
  idCliente INT NOT NULL REFERENCES cliente(idCliente) ON DELETE RESTRICT,
  idSuc INT NOT NULL REFERENCES sucursal(idSuc) ON DELETE RESTRICT,
  fechaPedido TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  total NUMERIC(10,2) NOT NULL,
  estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE_PAGO', -- PENDIENTE_PAGO, EN_REVISION, PAGADO, RECHAZADO, CANCELADO, EXPIRADO, LISTO, ENTREGADO
  fechaLimitePago TIMESTAMPTZ,
  comprobanteRuta VARCHAR(500),
  comprobanteMime VARCHAR(100),
  comprobanteNombre VARCHAR(255),
  fechaComprobante TIMESTAMPTZ,
  idEmpRevisa INT REFERENCES empleados(idEmp) ON DELETE SET NULL,
  fechaRevision TIMESTAMPTZ,
  motivoRechazo VARCHAR(255),
  idVenta INT REFERENCES venta(idVenta) ON DELETE SET NULL,
  bancoSnapshot VARCHAR(100),
  titularSnapshot VARCHAR(150),
  clabeSnapshot VARCHAR(18),
  numeroCuentaSnapshot VARCHAR(50),
  instruccionesSnapshot VARCHAR(1000),
  metadata JSONB DEFAULT '{}'::jsonb
);

-- Tabla: detalle_pedido_cliente
CREATE TABLE detalle_pedido_cliente (
  idDetallePedido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idPedido INT NOT NULL REFERENCES pedido_cliente(idPedido) ON DELETE CASCADE,
  idPro INT NOT NULL REFERENCES productos(idPro) ON DELETE RESTRICT,
  cantidad INT NOT NULL,
  precioUnitario NUMERIC(10,2) NOT NULL,
  subtotal NUMERIC(10,2) NOT NULL
);

-- ----------------------------------------------------------------------------
-- 3. Estrategia de Índices Avanzada (Postgres Pro: Compuestos, Parciales y GIN)
-- ----------------------------------------------------------------------------

-- Índices B-Tree en Foreign Keys y búsquedas generales
CREATE INDEX idx_productos_marca ON productos(idMarca);
CREATE INDEX idx_productos_categoria ON productos(idCat);
CREATE INDEX idx_detcompra_compra ON detcompra(idCompra);
CREATE INDEX idx_detcompra_producto ON detcompra(idPro);
CREATE INDEX idx_detventa_venta ON detventa(idVenta);
CREATE INDEX idx_detventa_producto ON detventa(idPro);
CREATE INDEX idx_detalle_pedido_idPedido ON detalle_pedido_cliente(idPedido);
CREATE INDEX idx_detalle_pedido_idPro ON detalle_pedido_cliente(idPro);
CREATE INDEX idx_movimiento_sesion ON movimiento_caja(idSesionCaja);

-- Índices Compuestos para Filtros y Ordenamiento Frecuente
CREATE INDEX idx_pedido_cliente_suc_fecha ON pedido_cliente(idSuc, fechaPedido DESC, idPedido DESC);
CREATE INDEX idx_pedido_cliente_cli_fecha ON pedido_cliente(idCliente, fechaPedido DESC, idPedido DESC);
CREATE INDEX idx_venta_suc_fecha ON venta(idSuc, fechaVenta DESC, idVenta DESC);
CREATE INDEX idx_sesion_caja_suc_fecha ON sesion_caja(idSuc, fechaHoraApertura DESC);

-- Índices Parciales (Optimizados para estados y registros activos)
CREATE INDEX idx_productos_activos ON productos(idPro, idMarca, idCat) WHERE activoPro = TRUE;
CREATE INDEX idx_pedidos_pendientes_expirables ON pedido_cliente(idPedido, idCliente, fechaLimitePago) WHERE estado = 'PENDIENTE_PAGO' AND comprobanteRuta IS NULL;
CREATE INDEX idx_pedidos_en_revision ON pedido_cliente(idPedido, idSuc, fechaRevision) WHERE estado = 'EN_REVISION';
CREATE INDEX idx_sesion_caja_abierta ON sesion_caja(idSesionCaja, idEmp, idSuc) WHERE estado = 'ABIERTA';
CREATE INDEX idx_empleados_activos ON empleados(idEmp, correoEmp, idCargo) WHERE estadoEmp = TRUE;
CREATE INDEX idx_clientes_activos ON cliente(idCliente, correoCliente) WHERE estadoCliente = TRUE;

-- Índice GIN para metadatos semiestructurados JSONB
CREATE INDEX idx_pedido_cliente_metadata ON pedido_cliente USING GIN (metadata);

-- ----------------------------------------------------------------------------
-- 4. Seeders de Datos Completos, Relacionados y Consistentes
-- ----------------------------------------------------------------------------

-- 4.1 Direcciones
INSERT INTO direccion (idDir, pais, estado, municipio, colonia, calle, noExt, noInt, codPostal) VALUES
(1, 'México', 'México', 'Toluca', 'Centro', 'Av. Hidalgo', '101', 'A', '50000'),
(2, 'México', 'México', 'Metepec', 'Providencia', 'Calle Benito Juárez', '204', NULL, '52140');

-- 4.2 Sucursales
INSERT INTO sucursal (idSuc, nombreSuc, descripcionSuc, telefonoSuc, correoSuc, paginaWebSuc, redSocialSuc, logoSuc, idDir) VALUES
(1, 'Doña paty', 'Tu mejor opción en abarrotes y productos de calidad', '7298456512', 'paty@gmail.com', 'https://tienda-donapaty.com', '@tiendadonapaty', 'https://tienda-donapaty-uploads.s3.us-east-1.amazonaws.com/tienda/logo-principal.png', 1);

-- 4.3 Cargos
INSERT INTO cargo (idCargo, nombreCargo, descripcionCargo, idSuc) VALUES
(1, 'ADMINISTRADOR', 'Acceso completo a la administración de la tienda', 1),
(2, 'CAJERO', 'Acceso al punto de venta y cobro de productos', 1);

-- 4.4 Empleados (Contraseñas con hash bcrypt)
INSERT INTO empleados (idEmp, nombreEmp, apellidoPatEmp, apellidoMatEmp, edadPer, generoPer, fechaIngreso, fechaEntrada, fechaSalida, correoEmp, contrasenaHash, estadoEmp, googleSub, telefono, fotoPerfil, idDir, idCargo) VALUES
(1, 'Administrador', 'Tienda', 'Principal', 35, 'Masculino', '2026-08-27', NULL, NULL, 'admin@gmail.com', '$2b$12$LrHug.oGSGD1HyV/DjAmweZMkuOpyaGAmLf7LVBvSBcSO7Gg.j4xu', TRUE, NULL, '7221234567', NULL, 1, 1),
(2, 'Diana Elena', 'Sanchez', 'Garcia', 28, 'Femenino', '2026-08-27', NULL, NULL, 'diana@gmail.com', '$2b$12$bxT2KK0A1pXZeMNdSlv6jeCAqy9cjqgGpPYCsWbnvWeZDcSQQ4KHa', TRUE, NULL, '7298456578', NULL, 2, 2),
(3, 'Dumb', 'User', 'Test', 25, 'Otro', '2026-08-29', NULL, NULL, 'dumb@user.com', '$2b$12$mcSBVhI4MURCB3ZqM.9tQuD9C7w3CZoMFDK01IM0.2TMqUAzkYlOK', TRUE, NULL, '7220000000', NULL, 1, 2);

-- 4.5 Clientes
INSERT INTO cliente (idCliente, nombreCliente, apellidoPatCliente, apellidoMatCliente, correoCliente, googleSub, fotoPerfil, estadoCliente, fechaRegistro, ultimoAcceso) VALUES
(1, 'Sandra', 'Sanchez Garcia', NULL, 'sandisg321@gmail.com', '112850685949394108985', 'https://lh3.googleusercontent.com/a/ACg8ocIJMPP9WjSS1Q24EvkIWBfw2WViU4TmsTmYSiDX6fsI3iew7lhadA=s96-c', TRUE, '2026-08-27 22:07:41+00', '2026-08-28 14:16:38+00'),
(2, 'Sandibell', 'Sánchez', NULL, 'sanchezsandibell0@gmail.com', '113116239049522862563', 'https://lh3.googleusercontent.com/a/ACg8ocJibMkXat3_rQQN_O4QFu0m5BgRVZ34steAf1Y7l93XZlaCOw=s96-c', TRUE, '2026-08-28 13:06:20+00', '2026-08-28 13:06:20+00'),
(3, 'Consultorios', 'Médicos', NULL, 'consultorios452@gmail.com', '105142001509885596007', 'https://lh3.googleusercontent.com/a/ACg8ocKkjRmRyBvGMUa8gupz-o0JYVKFLXqw0LjpH50A-MwA_dUT-w=s96-c', TRUE, '2026-08-28 13:14:27+00', '2026-08-28 13:14:27+00');

-- 4.6 Categorías
INSERT INTO categoria (idCat, nombreCat, descripCat) VALUES
(1, 'Bebidas y Refrescos', 'Refrescos carbonatados, jugos, aguas y bebidas energéticas'),
(2, 'Abarrotes y Alimentos', 'Despensa, latería, pastas, arroz, frijol y harinas'),
(3, 'Cuidado Personal', 'Desodorantes, jabones, lociones y cuidado corporal'),
(4, 'Botanas y Snacks', 'Papas, galletas, chocolates y golosinas');

-- 4.7 Marcas
INSERT INTO marca (idMarca, nombreMarca, descripMarca) VALUES
(1, 'Coca-Cola', 'Líder en refrescos y bebidas'),
(2, 'Sabritas', 'Botanas y papas saladas'),
(3, 'Nivea', 'Cuidado de la piel y desodorantes'),
(4, 'Obao / Garnier', 'Desodorantes y cuidado personal'),
(5, 'Bimbo', 'Panificación y pastelería');

-- 4.8 Proveedores
INSERT INTO proveedor (idProv, nombreProv, telefonoProv, correoProv, pagwebProv, redsocialProv, idDir) VALUES
(1, 'Distribuidora Femsa México', '7225551122', 'contacto@femsa.com.mx', 'https://femsa.com', '@femsamx', 1),
(2, 'Grupo Bimbo Toluca', '7225553344', 'ventas@bimbo.com.mx', 'https://bimbo.com.mx', '@bimbomx', 2);

-- 4.9 Productos
INSERT INTO productos (idPro, nombrePro, precioVentaPro, costoPro, existenciaPro, stockMinimoPro, tamanoPro, presentacionPro, tipoPro, codigoQR, skuPro, imagenPro, activoPro, idMarca, idCat) VALUES
(1, 'Coca-Cola Original', 50.00, 42.00, 24, 5, '3 Litros', 'Botella No Retornable', 'Refresco', '7501054549864', 'COCA-3L-NR', 'https://tienda-donapaty-uploads.s3.us-east-1.amazonaws.com/productos/coca-cola-3l.png', TRUE, 1, 1),
(2, 'Coca-Cola Sin Azúcar', 35.00, 28.00, 18, 4, '2 Litros', 'Botella No Retornable', 'Refresco', '7501054549871', 'COCA-2L-SA', 'https://tienda-donapaty-uploads.s3.us-east-1.amazonaws.com/productos/coca-cola-2l.png', TRUE, 1, 1),
(3, 'Desodorante Obao For Men', 30.00, 22.00, 15, 3, '65 g', 'Roll-on', 'Antitranspirante', '7509552876383', 'OBAO-65G-MEN', 'https://tienda-donapaty-uploads.s3.us-east-1.amazonaws.com/productos/obao-men.png', TRUE, 4, 3),
(4, 'Crema Corporal Nivea Milk Nutritiva', 85.00, 68.00, 10, 2, '400 ml', 'Botella Dosificadora', 'Cuidado Personal', '7501001150020', 'NIV-MILK-400', 'https://tienda-donapaty-uploads.s3.us-east-1.amazonaws.com/productos/nivea-milk.png', TRUE, 3, 3),
(5, 'Papas Sabritas Original Sal', 22.00, 17.50, 30, 6, '45 g', 'Bolsa', 'Botana', '7501011115552', 'SAB-SAL-45G', 'https://tienda-donapaty-uploads.s3.us-east-1.amazonaws.com/productos/sabritas-sal.png', TRUE, 2, 4);

-- 4.10 Configuración de Transferencia Bancaria
INSERT INTO configuracion_transferencia (idConfiguracion, idSuc, banco, titular, clabe, numeroCuenta, instrucciones, activo, fechaActualizacion) VALUES
(1, 1, 'BBVA', 'Sandra Sánchez García', '012180015250213582', '1525021358', 'Realiza tu transferencia a esta cuenta y sube una foto o captura de tu comprobante de pago para procesar tu pedido.', TRUE, CURRENT_TIMESTAMP);

-- 4.11 Sesiones de Caja
INSERT INTO sesion_caja (idSesionCaja, uuidSesionCaja, idEmp, idSuc, fechaHoraApertura, fondoInicial, fechaHoraCierre, totalVentas, totalEfectivo, totalTarjeta, totalTransferencia, totalIngresos, totalRetiros, efectivoEsperado, efectivoContado, diferencia, numeroVentas, estado, observaciones) VALUES
(1, '6486c696-8980-4e97-a52d-a4dc459bfc2c', 2, 1, '2026-08-27 18:48:38+00', 500.00, '2026-08-27 18:48:38+00', 0.00, 0.00, 0.00, 0.00, 100.00, 0.00, 600.00, 600.00, 0.00, 0, 'CERRADA', 'Validación automática'),
(2, 'f21925ec-1b32-48f7-a495-74082fb4eb1b', 2, 1, '2026-08-27 19:07:08+00', 500.00, '2026-08-27 19:07:08+00', 50.00, 50.00, 0.00, 0.00, 100.00, 50.00, 600.00, 600.00, 0.00, 1, 'CERRADA', 'Cierre final controlado'),
(3, 'ba95303a-6cc8-4d5f-89e3-775b4e94a2c1', 1, 1, '2026-08-28 09:00:00+00', 500.00, NULL, 150.00, 100.00, 50.00, 0.00, 50.00, 0.00, 650.00, NULL, NULL, 2, 'ABIERTA', 'Sesión de caja matutina activa');

-- 4.12 Movimientos de Caja
INSERT INTO movimiento_caja (idMovimientoCaja, uuidMovimientoCaja, idSesionCaja, tipoMovimiento, monto, concepto, fechaHora, idEmp) VALUES
(1, '991b1ef6-3c29-4528-b908-73e9ae001beb', 1, 'INGRESO', 100.00, 'Fondo adicional de cambio', '2026-08-27 18:48:38+00', 2),
(2, '80567e73-02af-42b9-9b9b-2b27fae00bed', 2, 'INGRESO', 100.00, 'Ingreso extraordinario', '2026-08-27 19:07:08+00', 2),
(3, 'f365a84b-482e-48da-98c8-a801daab7aa0', 2, 'RETIRO', 50.00, 'Pago menor a repartidor', '2026-08-27 19:07:08+00', 2),
(4, 'e451b72a-11af-49cf-93aa-5a821bb46311', 3, 'INGRESO', 50.00, 'Fondo de cambio monedas', '2026-08-28 09:30:00+00', 1);

-- 4.13 Ventas
INSERT INTO venta (idVenta, uuidVenta, fechaVenta, horaVenta, total, metodoPago, montoRecibido, cambio, estadoVenta, fechaCancelacion, motivoCancelacion, idEmpCancela, idEmp, idSuc, idSesionCaja) VALUES
(1, '593ad0da-7c98-47f6-b4b7-2a96d145da3f', '2026-08-27', '18:48:38', 50.00, 'EFECTIVO', 100.00, 50.00, 'CANCELADA', '2026-08-27 18:48:38+00', 'Validación automática de caja', 1, 2, 1, 1),
(2, '6fa2f32e-ebb3-401e-b39e-828f6023c900', '2026-08-27', '19:07:08', 50.00, 'EFECTIVO', 100.00, 50.00, 'COMPLETADA', NULL, NULL, NULL, 2, 1, 2),
(3, '978dfa1e-46a0-40db-a356-22d8be9b2a30', '2026-08-28', '10:15:00', 100.00, 'EFECTIVO', 100.00, 0.00, 'COMPLETADA', NULL, NULL, NULL, 1, 1, 3),
(4, '30e976ae-6cdf-4df8-8aaa-a42b38cf4322', '2026-08-28', '11:20:00', 50.00, 'TARJETA', 50.00, 0.00, 'COMPLETADA', NULL, NULL, NULL, 1, 1, 3);

-- 4.14 Detalle de Ventas
INSERT INTO detventa (idDetVenta, idVenta, idPro, cantidadDetVenta, precioUnitarioDetVenta, subtotalDetVenta) VALUES
(1, 1, 1, 1, 50.00, 50.00),
(2, 2, 1, 1, 50.00, 50.00),
(3, 3, 1, 2, 50.00, 100.00),
(4, 4, 1, 1, 50.00, 50.00);

-- 4.15 Pedidos de Clientes
INSERT INTO pedido_cliente (idPedido, uuidPedido, idCliente, idSuc, fechaPedido, total, estado, fechaLimitePago, comprobanteRuta, comprobanteMime, comprobanteNombre, fechaComprobante, idEmpRevisa, fechaRevision, motivoRechazo, idVenta, bancoSnapshot, titularSnapshot, clabeSnapshot, numeroCuentaSnapshot, instruccionesSnapshot) VALUES
(1, '0c96bab5-79fb-482b-b62b-37c8d669e555', 1, 1, '2026-08-28 13:11:46+00', 50.00, 'CANCELADO', '2026-08-28 15:11:46+00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BBVA', 'Sandra Sánchez García', '012180015250213582', '1525021358', 'Realiza tu transferencia a esta cuenta.'),
(2, '736d639a-7694-4de0-961f-9e97b2e90ef9', 1, 1, '2026-08-28 13:12:52+00', 100.00, 'LISTO', '2026-08-28 15:12:52+00', 'comprobantes/ec8938a3-369e-4679-a773-860ae4ab0087.pdf', 'application/pdf', 'ticket-comprobante.pdf', '2026-08-28 13:13:05+00', 1, '2026-08-28 13:25:34+00', NULL, 3, 'BBVA', 'Sandra Sánchez García', '012180015250213582', '1525021358', 'Realiza tu transferencia a esta cuenta.'),
(3, '290cda2d-7ad0-4298-8862-05e3b90d23f2', 2, 1, '2026-08-28 14:16:50+00', 80.00, 'EN_REVISION', '2026-08-28 16:16:50+00', 'comprobantes/f58912d4-482e-48da-98c8-a801daab7aa0.jpg', 'image/jpeg', 'comprobante-transferencia.jpg', '2026-08-28 14:30:00+00', NULL, NULL, NULL, NULL, 'BBVA', 'Sandra Sánchez García', '012180015250213582', '1525021358', 'Realiza tu transferencia a esta cuenta.'),
(4, '4412a81b-99f1-4c12-8822-11c8d771e899', 3, 1, '2026-08-28 15:00:00+00', 50.00, 'PENDIENTE_PAGO', CURRENT_TIMESTAMP + INTERVAL '2 hours', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BBVA', 'Sandra Sánchez García', '012180015250213582', '1525021358', 'Realiza tu transferencia a esta cuenta.');

-- 4.16 Detalle de Pedidos
INSERT INTO detalle_pedido_cliente (idDetallePedido, idPedido, idPro, cantidad, precioUnitario, subtotal) VALUES
(1, 1, 1, 1, 50.00, 50.00),
(2, 2, 1, 2, 50.00, 100.00),
(3, 3, 1, 1, 50.00, 50.00),
(4, 3, 3, 1, 30.00, 30.00),
(5, 4, 1, 1, 50.00, 50.00);

-- ----------------------------------------------------------------------------
-- 5. Sincronización de Secuencias de Identidad
-- ----------------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('direccion', 'iddir'), COALESCE(MAX(idDir), 1)) FROM direccion;
SELECT setval(pg_get_serial_sequence('sucursal', 'idsuc'), COALESCE(MAX(idSuc), 1)) FROM sucursal;
SELECT setval(pg_get_serial_sequence('cargo', 'idcargo'), COALESCE(MAX(idCargo), 1)) FROM cargo;
SELECT setval(pg_get_serial_sequence('empleados', 'idemp'), COALESCE(MAX(idEmp), 1)) FROM empleados;
SELECT setval(pg_get_serial_sequence('cliente', 'idcliente'), COALESCE(MAX(idCliente), 1)) FROM cliente;
SELECT setval(pg_get_serial_sequence('categoria', 'idcat'), COALESCE(MAX(idCat), 1)) FROM categoria;
SELECT setval(pg_get_serial_sequence('marca', 'idmarca'), COALESCE(MAX(idMarca), 1)) FROM marca;
SELECT setval(pg_get_serial_sequence('proveedor', 'idprov'), COALESCE(MAX(idProv), 1)) FROM proveedor;
SELECT setval(pg_get_serial_sequence('productos', 'idpro'), COALESCE(MAX(idPro), 1)) FROM productos;
SELECT setval(pg_get_serial_sequence('compra', 'idcompra'), COALESCE(MAX(idCompra), 1)) FROM compra;
SELECT setval(pg_get_serial_sequence('detcompra', 'iddetcompra'), COALESCE(MAX(idDetCompra), 1)) FROM detcompra;
SELECT setval(pg_get_serial_sequence('sesion_caja', 'idsesioncaja'), COALESCE(MAX(idSesionCaja), 1)) FROM sesion_caja;
SELECT setval(pg_get_serial_sequence('movimiento_caja', 'idmovimientocaja'), COALESCE(MAX(idMovimientoCaja), 1)) FROM movimiento_caja;
SELECT setval(pg_get_serial_sequence('venta', 'idventa'), COALESCE(MAX(idVenta), 1)) FROM venta;
SELECT setval(pg_get_serial_sequence('detventa', 'iddetventa'), COALESCE(MAX(idDetVenta), 1)) FROM detventa;
SELECT setval(pg_get_serial_sequence('configuracion_transferencia', 'idconfiguracion'), COALESCE(MAX(idConfiguracion), 1)) FROM configuracion_transferencia;
SELECT setval(pg_get_serial_sequence('pedido_cliente', 'idpedido'), COALESCE(MAX(idPedido), 1)) FROM pedido_cliente;
SELECT setval(pg_get_serial_sequence('detalle_pedido_cliente', 'iddetallepedido'), COALESCE(MAX(idDetallePedido), 1)) FROM detalle_pedido_cliente;

COMMIT;
